# ==========================================================
# ==              KONFIGURASI SERVER UTAMA                ==
# ==========================================================
server:
  port: 2333
  address: 0.0.0.0

# ==========================================================
# ==         KONFIGURASI INTI LAVALINK SERVER             ==
# ==========================================================
lavalink:
  server:
    # GANTI password ini dengan buatanmu sendiri yang kuat dan unik!
    password: "chiro666"
    sources:
      youtube: true
      bandcamp: true
      soundcloud: true
      twitch: true
      vimeo: true
      http: true
      local: false
    filters:
      volume: true
      equalizer: true
      karaoke: true
      timescale: true
      tremolo: true
      vibrato: true
      distortion: true
      rotation: true
      channelMix: true
      lowPass: true

    # Pengaturan Lanjutan
    gc-warnings: true

  # ==========================================================
  # ==      PLUGIN YANG AKAN DIMUAT OLEH LAVALINK           ==
  # ==========================================================
  plugins:
    # YouTube Plugin - WAJIB untuk YouTube support di Lavalink v4
    - dependency: "dev.lavalink.youtube:youtube-plugin:1.7.2"
      repository: "https://maven.lavalink.dev/releases"
      snapshot: false
    
    # LavaSrc Plugin untuk Spotify, Apple Music, dll
    - dependency: "com.github.topi314.lavasrc:lavasrc-plugin:4.7.3"
      repository: "https://jitpack.io"
      snapshot: false

# ==========================================================
# ==         KONFIGURASI SPESIFIK UNTUK PLUGIN            ==
# ==========================================================
plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    # Opsi untuk mengatasi rate limiting
    clients:
      - MUSIC
      - WEB
      - ANDROID_TESTSUITE
      - TVHTML5EMBEDDED
    
  lavasrc:
    sources:
      spotify: true
      applemusic: true
      deezer: false # Dinonaktifkan untuk menghindari error master key
      yandexmusic: false
    providers:
      - "ytmsearch:\"%ISRC%\""
      - "ytsearch:\"%ISRC%\""
      - "ytmsearch:%QUERY%"
      - "ytsearch:%QUERY%"
    spotify:
      # Ganti dengan kredensial dari dashboard developer Spotify-mu
      clientId: "GANTI_DENGAN_SPOTIFY_CLIENT_ID"
      clientSecret: "GANTI_DENGAN_SPOTIFY_CLIENT_SECRET"
      countryCode: "ID"
    applemusic:
      countryCode: "ID"

# ==========================================================
# ==                 KONFIGURASI LOGGING                  ==
# ==========================================================
logging:
  level:
    root: INFO
    lavalink: INFO

  file:
    path: ./logs/
  logback:
    rollingpolicy:
      max-file-size: 25MB
      max-history: 8

spring:
  main:
    banner-mode: "off"